name: StimmungsMessage
version: 1.3.0
main: net.ZeroBuddys.Stummungs.Main
api: ["1.0.8"]
author: ZeroBuddysYT
commands:
  dev:
    description: Der Developer Des Plugins
    usage: /dev
  plhelp:
    description: Der Plugin Help Command Des Plugins
    usage: /plhelp
  happy:
    description: Der Happy Command Des Plugins
    usage: /happy
  angry:
    description: Der Angry Command Des Plugins
    usage: /angry
  alone:
    description: Der Alone Command Des Plugins
    usage: /alone
  love:
    description: Der Love Command Des Plugins
    usage: /love
  sad:
    description: Der Sad Command Des Plugins
    usage: /sad
  frustraed:
    description: Der Frustraed Command Des Plugins
    usage: /frustraed
  nervous:
    description: Der Nervous Command Des Plugins
    usage: /nervous
  annoyed:
    description: Der Annoyed Command Des Plugins
    usage: /annoyed